# Generated by Django 4.0.5 on 2022-07-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_remove_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_link',
            field=models.URLField(help_text="Stores the listing product's image link", null=True),
        ),
    ]
