# Generated by Django 4.0.5 on 2022-07-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_link',
            field=models.URLField(blank=True, help_text="Stores the listing product's image link", null=True),
        ),
    ]
