# Generated by Django 4.0.5 on 2022-07-22 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the image for accessibility', max_length=200),
        ),
    ]
